=== AlexTS21/SemanticWeb/XML/familia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Tipo complejo reutilizable para personas -->
  <xs:complexType name="personaType">
    <xs:sequence>
      <!-- Permitir múltiples nombres -->
      <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="paterno" type="xs:string"/>
      <xs:element name="materno" type="xs:string"/>
      <xs:element name="edad" type="xs:positiveInteger"/>
      <!-- Formato dd-mm -->
      <xs:element name="fechaCumpleaños">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{2}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Elemento raíz -->
  <xs:element name="familia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="individio" type="personaType"/>
        <xs:element name="padre" type="personaType"/>
        <xs:element name="madre" type="personaType"/>
        <xs:element name="hermano" type="personaType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AlexTS21/SemanticWeb/XML/familia.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="familia.xsl"?>
<familia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="familia.xsd">
    <individio>
        <nombre>José</nombre>
        <nombre>Alejandro</nombre>
        <paterno>Tejeda</paterno>
        <materno>Sánchez</materno>
        <edad>21</edad>
        <fechaCumpleaños>21-12</fechaCumpleaños>
    </individio>
    <padre>
        <nombre>Cuitlahuac</nombre>
        <paterno>Tejeda</paterno>
        <materno>Hernandez</materno>
        <edad>51</edad>
        <fechaCumpleaños>28-12</fechaCumpleaños>
    </padre>
    <madre>
        <nombre>Gabriela</nombre>
        <nombre>Alejandra</nombre>
        <paterno>Sánchez</paterno>
        <materno>Camacho</materno>
        <edad>50</edad>
        <fechaCumpleaños>18-03</fechaCumpleaños>
    </madre>
    <hermano>
        <nombre>José</nombre>
        <nombre>Gabriel</nombre>
        <paterno>Tejeda</paterno>
        <materno>Sánchez</materno>
        <edad>23</edad>
        <fechaCumpleaños>19-02</fechaCumpleaños>
    </hermano>
</familia>
