=== AlexTS21/SemanticWeb/XML/recetario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="recetario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredientes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingrediente" maxOccurs="unbounded">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="cantidad" type="xs:positiveInteger" use="required"/>
                                                <xs:attribute name="unidad" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="litro"/>
                                                            <xs:enumeration value="unidad"/>
                                                            <xs:enumeration value="gramos"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="procedimiento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="paso" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="detalles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="duracion" type="xs:string"/>
                                        <xs:element name="porciones">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="unidad" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="vaso"/>
                                                            <xs:enumeration value="plato"/>
                                                            <xs:enumeration value="rebanada"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlexTS21/SemanticWeb/XML/recetario.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="recetario.xsl"?>
<recetario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recetario.xsd">
    <receta nombre="Agua de limon">
        <ingredientes>
            <ingrediente cantidad="1000" unidad="litro">
                agua
            </ingrediente>
            <ingrediente cantidad="5" unidad="unidad">
                limon
            </ingrediente>
            <ingrediente cantidad="150" unidad="gramos">
                azucar
            </ingrediente>
        </ingredientes>
        <procedimiento>
            <paso>Exprimir limones</paso>
            <paso>Combinar limones con agua</paso>
            <paso>Disolver el azucar en el agua</paso>
        </procedimiento>
        <detalles>
            <duracion>5 min</duracion>
            <porciones unidad="vaso">4</porciones>
        </detalles>
    </receta>

     <receta nombre="Sandwich de seitan">
        <ingredientes>
            <ingrediente cantidad="2" unidad="unidad">pan</ingrediente>
            <ingrediente cantidad="50" unidad="gramos">jamon</ingrediente>
            <ingrediente cantidad="20" unidad="gramos">queso</ingrediente>
        </ingredientes>
        <procedimiento>
            <paso>Poner una rebanada de pan</paso>
            <paso>Agregar seitan y queso</paso>
            <paso>Cubrir con otra rebanada</paso>
            <paso>Dorar el sandwich</paso>
        </procedimiento>
        <detalles>
            <duracion>5 min</duracion>
            <porciones unidad="plato">1</porciones>
        </detalles>
    </receta>

    <receta nombre="Ensalada">
        <ingredientes>
            <ingrediente cantidad="1" unidad="unidad">lechuga</ingrediente>
            <ingrediente cantidad="2" unidad="unidad">jitomate</ingrediente>
            <ingrediente cantidad="1" unidad="unidad">aguacate</ingrediente>
            <ingrediente cantidad="1" unidad="unidad">limon</ingrediente>
        </ingredientes>
        <procedimiento>
            <paso>Lavar y cortar las verduras</paso>
            <paso>Mezclar en un bowl</paso>
            <paso>Exprimir limon</paso>
        </procedimiento>
        <detalles>
            <duracion>7 min</duracion>
            <porciones unidad="plato">2</porciones>
        </detalles>
    </receta>

    <receta nombre="Pan con mantequilla">
        <ingredientes>
            <ingrediente cantidad="1" unidad="unidad">pan</ingrediente>
            <ingrediente cantidad="20" unidad="gramos">mantequilla</ingrediente>
        </ingredientes>
        <procedimiento>
            <paso>Tostar el pan si se desea</paso>
            <paso>Untar mantequilla sobre el pan</paso>
        </procedimiento>
        <detalles>
            <duracion>2 min</duracion>
            <porciones unidad="rebanada">1</porciones>
        </detalles>
    </receta>

    <receta nombre="Mollete de frijol">
        <ingredientes>
            <ingrediente cantidad="1" unidad="unidad">pan</ingrediente>
            <ingrediente cantidad="100" unidad="gramos">frijoles refritos</ingrediente>
            <ingrediente cantidad="30" unidad="gramos">queso manchego</ingrediente>
        </ingredientes>
        <procedimiento>
            <paso>Cortar pan por la mitad</paso>
            <paso>Untar frijoles en las rebanadas</paso>
            <paso>Agregar queso  encima</paso>
            <paso>Gratinar queso</paso>
        </procedimiento>
        <detalles>
            <duracion>7 min</duracion>
            <porciones unidad="rebanada">2</porciones>
        </detalles>
    </receta>
</recetario>
